Fail ./dt helper script when invoked outside the project root

diff --git a/dt b/dt
--- a/dt
+++ b/dt
@@ -2,6 +2,19 @@
 
 set -eu
 
+DT_ROOT="$(dirname "$0")"
+DT="$DT_ROOT/zig-out/bin/dt"
+
+# Running this outside the project root is likely an error:
+if [[ $DT_ROOT != . ]]; then
+  >&2 echo "ERROR: $0 is intended to be run when developing dt."
+  >&2 echo "If you're just trying to run a dt built from source:"
+  >&2 echo "- Navigate to $DT_ROOT"
+  >&2 echo "- Run './build release' to compile a release executable (Requires Zig 0.11.*)"
+  >&2 echo "- Use the result at: $DT"
+  exit 1
+fi
+
 zig build \
   && >&2 echo 'INFO: dt compiled (zig build exited successfully)' \
-  && exec rlwrap zig-out/bin/"$(basename "$0")" "$@"
+  && exec rlwrap "$DT" "$@"
